version: '3.9'

services:
  # Dịch vụ NestJS App
  api:
    build:
      context: . # Chỉ định Dockerfile nằm trong thư mục hiện tại
      dockerfile: Dockerfile
    container_name: nestjs_api
    restart: unless-stopped
    env_file:
      - ./.env # Nạp các biến môi trường từ file .env
    ports:
      - "3000:3000" # Map cổng 3000 của container ra cổng 3000 của máy host
    depends_on:
      - db
      - redis
      - minio
    #    volumes:
    # Nếu bạn cần mount code để development (hot-reload), bỏ comment dòng dưới.
    # Đối với production, không cần mount code vì đã được build vào image.
    # - .:/usr/src/app
    # - /usr/src/app/node_modules # Để tránh ghi đè node_modules của host

  # Dịch vụ Postgres
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data   # Lưu dữ liệu PostgreSQL vào thư mục thật

  # Dịch vụ Redis
  redis:
    image: redis:7.4
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data   # Dữ liệu Redis lưu trong volume
    command: [ "redis-server", "--appendonly", "yes" ]
    # Bật AOF để lưu dữ liệu bền vững hơn (so với chỉ RDB snapshot)

  # Dịch vụ Minio
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data

volumes:
  redis_data:
